# Generated by Django 3.1.7 on 2021-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210617_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr00',
            name='COMMENTS',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
