# Generated by Django 3.1.7 on 2021-06-22 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210617_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('MODEL_ID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('MODEL_NAME', models.CharField(max_length=100)),
                ('Vender_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('DEVICE_TYPE_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('IS_ACTIVE', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('COMMENTS', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETE_STATUS', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('CREATED_USER_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_USER_ID', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('UPDATED_DATE', models.DateField(blank=True, null=True)),
                ('MAX_ACCEPTED_READING', models.IntegerField()),
                ('ONNECTION_TYPE', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('Vender_ID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('VENDOR_NAME', models.CharField(max_length=100)),
                ('IS_ACTIVE', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('COMMENTS', models.CharField(blank=True, max_length=2000, null=True)),
                ('DELETE_STATUS', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('CREATED_USER_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_USER_ID', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('UPDATED_DATE', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AMR00',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
