# Generated by Django 3.1.7 on 2021-06-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210622_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='MAX_ACCEPTED_READING',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='ONNECTION_TYPE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
